title: "t3lesph0re's blog"
description: "offensive, mainly security."
url: "https://t3lesph0re.github.io"
baseurl: ""
lang: "en"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

rouge:
  style: base16.dark
